workflows:
  ios-build-release:
    name: iOS Build and Release
    triggering:
      events:
        - tag
      branch_patterns:
        - pattern: dev
          include: true
          source: true
      tag_patterns:
        - pattern: "+([0-9]).+([0-9]).+([0-9])"
          include: true
      cancel_previous_builds: true
    scripts:
      - name: git checkout
        script: git checkout dev
      - name: print
        script: |
           set -x
           echo "${FCI_BRANCH}"
      - name: env
        script: env
