workflows:
  ios-build-release:
    name: iOS Build and Release
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: master
          include: true
          source: true
      tag_patterns:
        - pattern: "v+([0-9]).+([0-9]).+([0-9])"
          include: true
      cancel_previous_builds: true
    scripts:
      - name: print
        script: |
           set -x
           echo "${FCI_BRANCH}"
      - name: env
        script: env
