workflows:
  ios-build-release:
    name: iOS Build and Release
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "+([0-9]).+([0-9]).+([0-9])"
          include: true
      cancel_previous_builds: true
    scripts:
      - name: git checkout
        script: |
          set -x
          git checkout master
          git fetch
          git checkout dev
      - name: print
        script: |
           set -x
           git branch -a
           echo "${FCI_BRANCH}"
      - name: env
        script: env
